### ISSUE TITLE
uniapp报错该应用不支持Grant_type:

### ISSUE THREAD

**Issue by werewolf666** [casdoor/casdoor-uniapp-example#3]
官方提供的demo跑不通，提示：该应用不支持Grant_type:
![image](https://github.com/casdoor/casdoor-uniapp-example/assets/35163330/dd5af412-d60f-46e4-a71e-2bcf007a0fda)

说明：
1，无论是用官方的后端地址和app还是用我自行部署的，都不行。
2，其他的SDK是可以正常登录的，比如后台的PHP的SDK。

**Comment by hsluoyz** [comment]
@werewolf666 fixed by: https://github.com/casdoor/casdoor-uniapp-example/commit/83b3f185f846e4ddad620f151d5d3a2fc956b11f
